# Generated by Django 5.2.7 on 2025-10-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSumasSaldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=200, verbose_name='Nombre del Reporte')),
                ('fecha_desde', models.DateField(verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha Hasta')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('incluir_saldos_cero', models.BooleanField(default=False, help_text='Incluir cuentas con saldo cero en el reporte', verbose_name='Incluir Saldos Cero')),
                ('solo_cuentas_movimiento', models.BooleanField(default=True, help_text='Incluir solo cuentas que tuvieron movimientos en el período', verbose_name='Solo Cuentas con Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Balance de Sumas y Saldos',
                'verbose_name_plural': 'Balances de Sumas y Saldos',
                'db_table': 'balances_sumas_saldos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('incluir_saldos_cero', models.BooleanField(default=False, verbose_name='Incluir Saldos Cero')),
                ('solo_cuentas_movimiento', models.BooleanField(default=True, verbose_name='Solo Cuentas con Movimiento')),
                ('agrupar_por_tipo', models.BooleanField(default=True, verbose_name='Agrupar por Tipo de Cuenta')),
                ('mostrar_saldos_anteriores', models.BooleanField(default=True, verbose_name='Mostrar Saldos Anteriores')),
                ('mostrar_movimientos', models.BooleanField(default=True, verbose_name='Mostrar Movimientos')),
                ('formato_numero', models.CharField(default='0,000.00', max_length=20, verbose_name='Formato de Números')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Balance',
                'verbose_name_plural': 'Configuraciones de Balance',
                'db_table': 'configuraciones_balance',
            },
        ),
        migrations.CreateModel(
            name='DetalleBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Anterior')),
                ('movimientos_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Movimientos Debe')),
                ('movimientos_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Movimientos Haber')),
                ('saldo_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Debe')),
                ('saldo_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Haber')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final')),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición en el reporte', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de Balance',
                'verbose_name_plural': 'Detalles de Balance',
                'db_table': 'detalles_balance',
                'ordering': ['balance', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ResumenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=20, verbose_name='Tipo de Cuenta')),
                ('total_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Debe')),
                ('total_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Haber')),
                ('saldo_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Neto')),
                ('cantidad_cuentas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Cuentas')),
            ],
            options={
                'verbose_name': 'Resumen de Balance',
                'verbose_name_plural': 'Resúmenes de Balance',
                'db_table': 'resumenes_balance',
            },
        ),
    ]
