# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balancesumasysaldos', '0001_initial'),
        ('plancuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesumassaldos',
            name='usuario_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generación'),
        ),
        migrations.AddField(
            model_name='detallebalance',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='balancesumasysaldos.balancesumassaldos', verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='detallebalance',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plancuentas.plancuentas', verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='resumenbalance',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='balancesumasysaldos.balancesumassaldos', verbose_name='Balance'),
        ),
        migrations.AlterUniqueTogether(
            name='detallebalance',
            unique_together={('balance', 'cuenta')},
        ),
        migrations.AlterUniqueTogether(
            name='resumenbalance',
            unique_together={('balance', 'tipo_cuenta')},
        ),
    ]
