# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta (ej: 1.1.01.001)', max_length=20, unique=True, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuenta', max_length=200, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio Neto'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo de Venta')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=20, verbose_name='Naturaleza')),
                ('nivel', models.PositiveIntegerField(help_text='Nivel jerárquico de la cuenta (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la cuenta', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la cuenta está disponible para uso', verbose_name='Cuenta Activa')),
                ('permite_movimiento', models.BooleanField(default=True, help_text='Indica si se pueden registrar movimientos en esta cuenta', verbose_name='Permite Movimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('cuenta_padre', models.ForeignKey(blank=True, help_text='Cuenta de nivel superior en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_hijas', to='plancuentas.plancuentas', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'db_table': 'plan_cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Inicial')),
                ('fecha', models.DateField(verbose_name='Fecha del Saldo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_iniciales', to='plancuentas.plancuentas', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Saldo Inicial',
                'verbose_name_plural': 'Saldos Iniciales',
                'db_table': 'saldos_iniciales',
            },
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['codigo'], name='plan_cuenta_codigo_d8ef25_idx'),
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['tipo'], name='plan_cuenta_tipo_e4a072_idx'),
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['nivel'], name='plan_cuenta_nivel_8ec669_idx'),
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['activa'], name='plan_cuenta_activa_ffba95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoinicial',
            unique_together={('cuenta', 'fecha')},
        ),
    ]
