# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único del comprobante', max_length=20, unique=True, verbose_name='Número de Comprobante')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Comprobante de Ingreso'), ('EGRESO', 'Comprobante de Egreso'), ('DIARIO', 'Asiento de Diario'), ('TRASPASO', 'Asiento de Traspaso'), ('AJUSTE', 'Asiento de Ajuste')], max_length=20, verbose_name='Tipo de Comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha del Comprobante')),
                ('concepto', models.TextField(help_text='Descripción del comprobante', verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('total_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Debe')),
                ('total_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Haber')),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia externa', max_length=100, null=True, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'comprobantes',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto del Movimiento')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haber')),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición en el comprobante', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobantes',
                'db_table': 'detalles_comprobantes',
                'ordering': ['comprobante', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Comprobante de Ingreso'), ('EGRESO', 'Comprobante de Egreso'), ('DIARIO', 'Asiento de Diario'), ('TRASPASO', 'Asiento de Traspaso'), ('AJUSTE', 'Asiento de Ajuste')], max_length=20, unique=True, verbose_name='Tipo de Comprobante')),
                ('prefijo', models.CharField(blank=True, help_text='Prefijo para el número (ej: CI, CE, AD)', max_length=10, null=True, verbose_name='Prefijo')),
                ('siguiente_numero', models.PositiveIntegerField(default=1, verbose_name='Siguiente Número')),
                ('formato', models.CharField(default='000000', help_text='Formato del número (ej: 000000 para 6 dígitos)', max_length=20, verbose_name='Formato')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Secuencia de Comprobante',
                'verbose_name_plural': 'Secuencias de Comprobantes',
                'db_table': 'secuencias_comprobantes',
            },
        ),
    ]
