# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0001_initial'),
        ('plancuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aprobación'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plancuentas.plancuentas', verbose_name='Cuenta Contable'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['numero'], name='comprobante_numero_75092e_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['tipo'], name='comprobante_tipo_c37ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['fecha'], name='comprobante_fecha_996df2_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['estado'], name='comprobante_estado_788330_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecomprobante',
            index=models.Index(fields=['comprobante'], name='detalles_co_comprob_903ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecomprobante',
            index=models.Index(fields=['cuenta'], name='detalles_co_cuenta__cf925e_idx'),
        ),
    ]
