# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plancuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('incluir_saldos_cero', models.BooleanField(default=False, verbose_name='Incluir Saldos Cero')),
                ('agrupar_por_tipo', models.BooleanField(default=True, verbose_name='Agrupar por Tipo de Cuenta')),
                ('mostrar_cuentas_principales', models.BooleanField(default=True, verbose_name='Mostrar Solo Cuentas Principales')),
                ('formato_numero', models.CharField(default='0,000.00', max_length=20, verbose_name='Formato de Números')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Estado',
                'verbose_name_plural': 'Configuraciones de Estado',
                'db_table': 'configuraciones_estado',
            },
        ),
        migrations.CreateModel(
            name='EstadoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado patrimonial', max_length=200, verbose_name='Nombre del Estado')),
                ('fecha', models.DateField(help_text='Fecha de corte del estado patrimonial', verbose_name='Fecha del Estado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Estado Patrimonial',
                'verbose_name_plural': 'Estados Patrimoniales',
                'db_table': 'estados_patrimoniales',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado de resultados', max_length=200, verbose_name='Nombre del Estado')),
                ('fecha_desde', models.DateField(verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha Hasta')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Estado de Resultados',
                'verbose_name_plural': 'Estados de Resultados',
                'db_table': 'estados_resultados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ResumenFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Activos')),
                ('total_pasivos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Pasivos')),
                ('total_patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Patrimonio')),
                ('ratio_liquidez', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Ratio de Liquidez')),
                ('ratio_endeudamiento', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Ratio de Endeudamiento')),
            ],
            options={
                'verbose_name': 'Resumen Financiero',
                'verbose_name_plural': 'Resúmenes Financieros',
                'db_table': 'resumenes_financieros',
            },
        ),
        migrations.CreateModel(
            name='DetalleEstadoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final')),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición en el estado', verbose_name='Orden')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plancuentas.plancuentas', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Detalle de Estado Patrimonial',
                'verbose_name_plural': 'Detalles de Estado Patrimonial',
                'db_table': 'detalles_estado_patrimonial',
                'ordering': ['estado', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final')),
                ('orden', models.PositiveIntegerField(help_text='Orden de aparición en el estado', verbose_name='Orden')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plancuentas.plancuentas', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Detalle de Estado de Resultados',
                'verbose_name_plural': 'Detalles de Estado de Resultados',
                'db_table': 'detalles_estado_resultados',
                'ordering': ['estado', 'orden'],
            },
        ),
    ]
