# Generated by Django 5.2.7 on 2025-10-19 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadopatrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopatrimonial',
            name='usuario_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generación'),
        ),
        migrations.AddField(
            model_name='detalleestadopatrimonial',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='estadopatrimonio.estadopatrimonial', verbose_name='Estado Patrimonial'),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='usuario_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generación'),
        ),
        migrations.AddField(
            model_name='detalleestadoresultados',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='estadopatrimonio.estadoresultados', verbose_name='Estado de Resultados'),
        ),
        migrations.AddField(
            model_name='resumenfinanciero',
            name='estado_patrimonial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='estadopatrimonio.estadopatrimonial', verbose_name='Estado Patrimonial'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleestadopatrimonial',
            unique_together={('estado', 'cuenta')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleestadoresultados',
            unique_together={('estado', 'cuenta')},
        ),
    ]
